### ISSUE TITLE
[ADD] S3 연결 설정 및 코드 수정

### ISSUE THREAD

**Issue by ningpop** [Showme-Prologue/Prologue-BE#10]
## 📝  To-do

- [x] S3 생성
- [x] S3 - Django 연결 설정
- [x] 이미지 업로드 테스트
- [x] 이미지 조회 테스트
